name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Additional Packages
        run: |
          npm install cypress --save-dev
          npm install xlsx --save
          npm install axios --save
          npm install @cypress/code-coverage --save-dev
          npm install cypress-file-upload --save-dev

      - name: Add Additional Packages (npm add)
        run: |
          npm add cypress
          npm add xlsx
          npm add axios
          npm add @cypress/code-coverage
          npm add cypress-file-upload

      - name: Cypress Package Initialization
        run: npx cypress init

      - name: Run Cypress Tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}  # Set your GitHub secrets for username and password
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx cypress run --spec "cypress/e2e/work_flow.cy.js" --config-file=./cypress.config.cjs

      - name: Upload Cypress test artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**

      - name: Upload Cypress video artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**
